//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.EdgeFavorite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.EdgeFavorite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL (Ctrl+C).
        /// </summary>
        internal static string Action_CopyUrl {
            get {
                return ResourceManager.GetString("Action_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all ({0}) (Ctrl+O).
        /// </summary>
        internal static string Action_OpenAll {
            get {
                return ResourceManager.GetString("Action_OpenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all ({0}) in InPrivate window (Ctrl+P).
        /// </summary>
        internal static string Action_OpenAllPrivate {
            get {
                return ResourceManager.GetString("Action_OpenAllPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all ({0}) in new window (Ctrl+N).
        /// </summary>
        internal static string Action_OpenAllWindow {
            get {
                return ResourceManager.GetString("Action_OpenAllWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in InPrivate window (Ctrl+P).
        /// </summary>
        internal static string Action_OpenPrivate {
            get {
                return ResourceManager.GetString("Action_OpenPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window (Ctrl+N).
        /// </summary>
        internal static string Action_OpenWindow {
            get {
                return ResourceManager.GetString("Action_OpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string Channel_Beta {
            get {
                return ResourceManager.GetString("Channel_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canary.
        /// </summary>
        internal static string Channel_Canary {
            get {
                return ResourceManager.GetString("Channel_Canary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.
        /// </summary>
        internal static string Channel_Dev {
            get {
                return ResourceManager.GetString("Channel_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable.
        /// </summary>
        internal static string Channel_Stable {
            get {
                return ResourceManager.GetString("Channel_Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite: {0} - {1}.
        /// </summary>
        internal static string FavoriteResult_Profile_Subtitle {
            get {
                return ResourceManager.GetString("FavoriteResult_Profile_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite: {0}.
        /// </summary>
        internal static string FavoriteResult_Subtitle {
            get {
                return ResourceManager.GetString("FavoriteResult_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: {0} - {1}.
        /// </summary>
        internal static string FolderResult_Profile_Subtitle {
            get {
                return ResourceManager.GetString("FolderResult_Profile_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: {0}.
        /// </summary>
        internal static string FolderResult_Subtitle {
            get {
                return ResourceManager.GetString("FolderResult_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the corresponding version or switch channel from the plugin settings.
        /// </summary>
        internal static string MissingChannel_Subtitle {
            get {
                return ResourceManager.GetString("MissingChannel_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Edge {0} not found.
        /// </summary>
        internal static string MissingChannel_Title {
            get {
                return ResourceManager.GetString("MissingChannel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the channel to use..
        /// </summary>
        internal static string Option_Channel_Description {
            get {
                return ResourceManager.GetString("Option_Channel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Option_Channel_Label {
            get {
                return ResourceManager.GetString("Option_Channel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents favorites from the specified profiles to be loaded. Add one profile per line..
        /// </summary>
        internal static string Option_ExcludedProfiles_Description {
            get {
                return ResourceManager.GetString("Option_ExcludedProfiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded profiles.
        /// </summary>
        internal static string Option_ExcludedProfiles_Label {
            get {
                return ResourceManager.GetString("Option_ExcludedProfiles_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: Personal.
        /// </summary>
        internal static string Option_ExcludedProfiles_Placeholder {
            get {
                return ResourceManager.GetString("Option_ExcludedProfiles_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate the folder tree when searching..
        /// </summary>
        internal static string Option_SearchTree_Description {
            get {
                return ResourceManager.GetString("Option_SearchTree_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search as tree.
        /// </summary>
        internal static string Option_SearchTree_Label {
            get {
                return ResourceManager.GetString("Option_SearchTree_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Microsoft Edge favorites.
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Favorite.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
    }
}
